### ISSUE TITLE
`npm install` fails on dependency

### ISSUE THREAD

**Issue by coltron-code** [paytonjewell/ReactPortfolioTemplate#6]
### Summary
When running `npm install` build hangs on dependency `@mui/icons-materialw`, and fails. 

**System Info**
- Running on Mac OSX M1.
- Node v18.2.0

**Comment by artemnovitckii** [comment]
@paytonjewell I have found the fix for the issue. The issue was that node-saas is deprecated and only supports node  v14.x.x. So for this project to run you gotta use that version.
Also have a look at this https://stackoverflow.com/questions/71119253/getting-errors-while-installing-node-sass

**Comment by paytonjewell** [comment]
Awesome find, thank you! @artemnovitckii So do you think it would be best for me to put in the readme that this project requires use of Node 14?

**Comment by artemnovitckii** [comment]
yeah for sure just add to readme :)
